lsi: false
highlighter: pygments
comments: true
markdown: redcarpet
name: rodrigo braga
url: "http://www.rbraga.com"
description: tactical code
author: Rodrigo Braga
permalink: pretty
exclude: ['node_modules', 'bower_components']